from User import User
percy = User("Percy", "che.percy.l@gmail.com")
mery = User("Mery", "meryche@gmail.com")
samantha = User("Samantha", "samantha.che.inolopu@gmail.com")
percy.make_deposit("Savings", 100).make_deposit("Savings", 200).make_deposit("Savings", 300).make_transfer(mery, "Savings", 100)
mery.make_deposit("Savings", 100).make_deposit("Savings", 200).make_transfer(samantha, "Savings", 100).make_transfer(percy, "Savings", 100)
percy.show_bank_account_balance("Savings")
mery.show_bank_account_balance("Savings")
samantha.show_bank_account_balance("Savings")
samantha.make_deposit("Savings", 400).make_transfer(percy, "Savings", 100).make_transfer(mery, "Savings", 100).make_transfer(percy, "Savings", 200)
percy.show_bank_account_balance("Savings")
mery.show_bank_account_balance("Savings")
samantha.show_bank_account_balance("Savings")
percy.make_withdrawal("Savings", 100)
mery.make_withdrawal("Savings", 100)
samantha.make_withdrawal("Savings", 100)
percy.show_bank_account_balance("Savings")
mery.show_bank_account_balance("Savings")
samantha.show_bank_account_balance("Savings")

percy.make_deposit("Checking", 100).make_deposit("Checking", 200).make_deposit("Checking", 300).make_transfer(mery, "Checking", 100)
mery.make_deposit("Checking", 100).make_deposit("Checking", 200).make_transfer(samantha, "Checking", 100).make_transfer(percy, "Checking", 100)
percy.show_bank_account_balance("Checking")
mery.show_bank_account_balance("Checking")
samantha.show_bank_account_balance("Checking")
samantha.make_deposit("Checking", 400).make_transfer(percy, "Checking", 100).make_transfer(mery, "Checking", 100).make_transfer(percy, "Checking", 200)
percy.show_bank_account_balance("Checking")
mery.show_bank_account_balance("Checking")
samantha.show_bank_account_balance("Checking")
percy.make_withdrawal("Checking", 100)
mery.make_withdrawal("Checking", 100)
samantha.make_withdrawal("Checking", 100)
percy.show_bank_account_balance("Checking")
mery.show_bank_account_balance("Checking")
samantha.show_bank_account_balance("Checking")